In [1]:
import requests
import xml.etree.ElementTree as ET

In [2]:
res = requests.get("https://g1.globo.com/sitemap/g1/2026/04/13_1.xml")
root = ET.fromstring(res.content)
root

In [3]:
root.tag

'{http://www.sitemaps.org/schemas/sitemap/0.9}urlset'

In [4]:
import xmltodict

In [5]:
data = xmltodict.parse(res.content)
data

{'urlset': {'@xmlns': 'http://www.sitemaps.org/schemas/sitemap/0.9',
  '@xmlns:xhtml': 'http://www.w3.org/1999/xhtml',
  '@xmlns:image': 'http://www.google.com/schemas/sitemap-image/1.1',
  'url': [{'loc': 'https://g1.globo.com/sp/sorocaba-jundiai/noticia/2026/04/13/adolescente-morre-por-h1n1-em-sorocaba.ghtml',
    'lastmod': '2026-04-14T17:30:15.338000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/5WMQUedvi2zqpNQj2e_POdc2RCs=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2023/T/d/RKq3A5R1uhACEssrjRpg/vacina-sorocaba.jpg'}},
   {'loc': 'https://g1.globo.com/sp/vale-do-paraiba-regiao/noticia/2026/04/13/exportacoes-recuam-2percent-no-primeiro-trimestre-de-2026-no-vale-do-paraiba-e-regiao-bragantina.ghtml',
    'lastmod': '2026-04-13T23:56:07.685000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/G1v13EIEXgZUaPQyp-3jJBT-4Es=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/A/0/P7oAY3TpGaDEh1MihIEg/weq.jpg'}},
   {'loc': 'https://g1.globo.com/jornal-nacional/noticia/2026/04/13/trump-chama-leao-xiv-de-fraco-e-pessimo-papa-reage-e-diz-que-vai-seguir-firme-contra-a-guerra.ghtml',
    'lastmod': '2026-04-14T00:11:40.971000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/Q12VKbgrhSwLK-jhWUXrUpUXmfw=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/a/A/4LkCkZRN2E9lHWWGk5vQ/globo-canal-4-20260413-2000-frame-65795.jpeg'}},
   {'loc': 'https://g1.globo.com/sp/bauru-marilia/noticia/2026/04/13/marilia-sanciona-lei-que-permite-enterro-de-caes-e-gatos-em-jazigos-de-tutores-projeto-e-aprovado-na-camara-em-bauru.ghtml',
    'lastmod': '2026-04-13T23:48:51.106000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/wNIaofRMl5fL1HaDvwZcZI82l6M=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/u/j/Ej9JXpR3urbLLgQv5hLg/fotojet-51-.jpg'}},
   {'loc': 'https://g1.globo.com/mt/mato-grosso/noticia/2026/04/13/video-onibus-e-destruido-por-incendio-na-br-364-em-mt.ghtml',
    'lastmod': '2026-04-13T23:46:54.569000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/GnXoaLlTrPJZ6vUqX5duDhOMoKI=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/Q/4/1Ro5aZSkyIVK9vEMb7Mw/videos-g1-2026-04-13t192410.396.gif'}},
   {'loc': 'https://g1.globo.com/sp/santos-regiao/noticia/2026/04/13/medico-e-detido-acusado-de-agredir-companheira-no-interior-de-sp.ghtml',
    'lastmod': '2026-04-13T23:46:10.375000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/6qJew7GVPVsCkadVIIqQaUv7G6k=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/3/v/8LdxxQSzmszaFKaL54TQ/caso-medico-preso.jpg'}},
   {'loc': 'https://g1.globo.com/politica/noticia/2026/04/13/apos-pressao-do-governo-projeto-que-regulamenta-atividade-de-entregadores-e-motoristas-sai-de-pauta-na-camara.ghtml',
    'lastmod': '2026-04-14T00:30:59.380000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/0bHENNtMwOl4AZeb8oeJ94COELQ=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2020/b/j/dotgNvSUeptoZW6L8QTg/2020-07-01t191927z-1632778232-rc2jkh9ae6ex-rtrmadp-3-brazil-uber-protests.jpg'}},
   {'loc': 'https://g1.globo.com/ce/ceara/noticia/2026/04/13/zoologico-de-fortaleza-vai-fechar-durante-dois-dias-apos-lotacoes-registradas-desde-a-inauguracao.ghtml',
    'lastmod': '2026-04-13T23:44:31.476000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/pQyponardJnuyvPIBPkCudJSFWQ=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/v/h/mQsotoT5GOYy1H1FpV9A/zoo-lotado.jpg'}},
   {'loc': 'https://g1.globo.com/pi/piaui/noticia/2026/04/13/medico-moto-atingida-acidente.ghtml',
    'lastmod': '2026-04-13T23:40:04.469000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/XtWCwMHor8SBS2B7bvRGMnpmz1M=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/4/U/yqX11GQ02LYhZbNjOx0A/edicao-imagens-g1-2-.jpg'}},
   {'loc': 'https://g1.globo.com/ac/acre/noticia/2026/04/13/moradores-reclamam-de-vizinho-que-acumula-lixo-e-entulho-em-casa-no-acre-extremamente-insalubre.ghtml',
    'lastmod': '2026-04-13T23:37:48.233000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/LEEjv_oLwdrZiEdfksBbl8tWlnc=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/E/5/DGVA9tQzqAM68BA7Q0PQ/midia-de-distribuicao-g1-29-.jpg'}},
   {'loc': 'https://g1.globo.com/am/amazonas/noticia/2026/04/13/corregedoria-do-tribunal-de-justica-do-amazonas-analisa-omissao-de-juiz-do-careiro-apos-demora-em-decisao-diz-presidente.ghtml',
    'lastmod': '2026-04-13T23:41:11.297000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/S-3L3Ezcyu38X04iXgGxXVrplhA=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2022/s/U/tAOqqWQUGc3tUXFK47Bg/tremor-no-tjam-foto-rede-amazonica.jpg'}},
   {'loc': 'https://g1.globo.com/ms/mato-grosso-do-sul/noticia/2026/04/13/pm-da-reserva-tentar-matar-esposa-a-tiros-e-vitima-escapa-ao-pular-muro-de-casa-e-pedir-socorro-em-bar-de-ms.ghtml',
    'lastmod': '2026-04-14T13:05:19.571000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/TdQpbyeT3IkCBO85Mmf2VisQS6w=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/A/a/MnD6vYS0CjCLHHNvrGAA/para-o-g1-2026-04-13t190146.711.jpg'}},
   {'loc': 'https://g1.globo.com/pa/para/noticia/2026/04/13/apos-dois-anos-policia-federal-ainda-tenta-identificar-corpos-encontrados-em-barco-a-deriva-no-para.ghtml',
    'lastmod': '2026-04-14T00:08:08.178000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/e7ikmTz9PSTiXUzAbiHDKkGAvQ8=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2024/M/S/p4L037SROFfLYo4virAg/barco.jpg'}},
   {'loc': 'https://g1.globo.com/mg/minas-gerais/noticia/2026/04/13/camara-de-bh-aprova-em-1o-turno-ampliacao-de-isencao-de-taxa-para-habitacoes-sociais.ghtml',
    'lastmod': '2026-04-13T23:32:29.186000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/t5ZaEBBlwp4kKtrniGLPJTpY_1A=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/n/k/25jpFQSO6nTHlqniZmPQ/55205669556-701486dd4f-k.jpg'}},
   {'loc': 'https://g1.globo.com/sp/ribeirao-preto-franca/noticia/2026/04/13/familia-de-empresario-morto-baleado-em-bar-no-rio-de-janeiro-repudia-versao-de-que-vitima-se-envolveu-em-confusao.ghtml',
    'lastmod': '2026-04-13T23:31:48.147000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/p2o5GURWFm2jxn6XbP8mReGNuYw=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/O/o/ZewVdaRvOf2d4pfdN19g/rj2-limpo-20260413-1830-frame-76893.jpeg'}},
   {'loc': 'https://g1.globo.com/pe/caruaru-regiao/playlist/videos-ab2-de-segunda-feira-13-de-abril-de-2026.ghtml',
    'lastmod': '2026-04-13T23:30:33.859000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/PN0MsSnr8RHoipi0ukW8kk_cYCU=/s01.video.glbimg.com/deo/vi/94/21/14522194'}},
   {'loc': 'https://g1.globo.com/ba/feira-de-santana-regiao/edicao/2026/04/13/videos-do-g1-e-tv-subae-segunda-feira-13-de-abril-de-2026.ghtml',
    'lastmod': '2026-04-13T23:30:13.772000+00:00'},
   {'loc': 'https://g1.globo.com/sp/sorocaba-jundiai/noticia/2026/04/13/mulher-morta-facadas-briga-vizinhos-salto.ghtml',
    'lastmod': '2026-04-13T23:29:04.282000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/LzRb6aIhoeq2VGAqUe-Sb6YY2Ps=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2025/1/k/6yCSAPTiymBQSmD8ADBg/design-sem-nome-2025-10-30t131052.631.png'}},
   {'loc': 'https://g1.globo.com/pe/pernambuco/videos-ne2/playlist/videos-ne2-de-segunda-feira-13-de-abril-de-2026.ghtml',
    'lastmod': '2026-04-13T23:27:05.571000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/7I9trcN0QPlAyQKmFUxkG3pSDKo=/s01.video.glbimg.com/deo/vi/62/21/14522162'}},
   {'loc': 'https://g1.globo.com/sp/sao-paulo/eleicoes/2026/noticia/2026/04/13/uniao-brasil-em-sp-critica-articulacao-para-ciro-nogueira-liderar-federacao-com-pp-e-fala-em-risco-de-ruptura.ghtml',
    'lastmod': '2026-04-14T09:49:18.423000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/izpgz7VGyP87T2VoQt4C6-R9Xik=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2025/H/H/tnFyc7RIy0qK2tHE4XKg/54614219965-f976fb18f5-o.jpg'}},
   {'loc': 'https://g1.globo.com/mg/sul-de-minas/noticia/2026/04/13/ministerio-publico-ajuiza-acao-para-preservar-atividades-da-unincor-em-tres-coracoes-mg.ghtml',
    'lastmod': '2026-04-13T23:23:22.842000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/xlqlgCsXOhMK4Kkhu8MWEadVYJ0=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/e/Z/xXMJbqSvA6CAZ8AMv8mw/unincor.png'}},
   {'loc': 'https://g1.globo.com/rj/sul-do-rio-costa-verde/noticia/2026/04/13/acidente-entre-motos-deixa-dois-feridos-na-br-393-em-tres-rios.ghtml',
    'lastmod': '2026-04-13T23:22:38.333000+00:00'},
   {'loc': 'https://g1.globo.com/pb/paraiba/noticia/2026/04/13/buscas-por-homem-que-desapareceu-em-acude-no-agreste-da-pb-sao-suspensas-e-devem-ser-retomadas-nesta-terca-14.ghtml',
    'lastmod': '2026-04-13T23:20:09.079000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/BcnWgKLhzYNPKZ3BeKlo69hpz9U=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/y/N/HjfcOjRyAqIwVg4s19BA/captura-de-tela-1-.png'}},
   {'loc': 'https://g1.globo.com/mg/triangulo-mineiro/noticia/2026/04/13/video-assaltantes-armados-com-um-revolver-roubam-mercado-e-deixam-prejuizo-de-r-1-mil-no-interior-de-mg.ghtml',
    'lastmod': '2026-04-13T23:44:44.842000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/VH50F61pSGjl0nhH1z7pih-IFKo=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/g/O/4biBEDT7KNzUchhJV1Yg/dupla-de-encapuzados-com-arma-rouba-mercado-e-deixa-prejuizo-no-interior-de-mg.png'}},
   {'loc': 'https://g1.globo.com/df/distrito-federal/noticia/2026/04/13/maior-chacina-do-df-primeiro-dia-de-julgamento-ultrapassa-10-horas-juri-sera-retomado-nesta-terca.ghtml',
    'lastmod': '2026-04-13T23:15:04.646000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/z-khyePVtW4Jw9lfcyNfKe4bXIQ=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2023/o/Z/0Z891jQ3AdgmOxfbBSrw/a0600-bddf-limpo-16012023-frame-104783.jpeg'}},
   {'loc': 'https://g1.globo.com/rj/regiao-serrana/noticia/2026/04/13/lacres-de-latinhas-viram-cadeiras-de-rodas-para-doacao-em-petropolis.ghtml',
    'lastmod': '2026-04-13T23:13:56.353000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/QuHYbJZ9rIXBlAXBqTv1yelNGz0=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/o/d/kt8qqTSsWBTyAbD1TzCg/latinha.jpg'}},
   {'loc': 'https://g1.globo.com/sp/bauru-marilia/noticia/2026/04/13/acidentes-em-rodovias-deixam-feridos-em-lencois-paulista-e-iacri-motoristas-sao-investigados.ghtml',
    'lastmod': '2026-04-13T23:08:29.168000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/6F3TwXi4aUMYQKuAZHy0IDv8VCA=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2025/D/I/fQyA7eTrisKAA76uH8Hg/sct.png'}},
   {'loc': 'https://g1.globo.com/sp/santos-regiao/noticia/2026/04/13/preso-morre-com-meningite-bacteriana-e-visitas-sao-suspensas-no-cdp-de-sao-vicente-diz-sap.ghtml',
    'lastmod': '2026-04-13T23:07:53.973000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/5KJjZ7Zm92uIHzCj2TJduHRXBP8=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/L/8/anW4QiTJGRk4i8Bg0qrw/visita-suspensa-1-.jpg'}},
   {'loc': 'https://g1.globo.com/sp/sorocaba-jundiai/noticia/2026/04/13/justica-mantem-condenacao-reus-tribunal-crime-sorocaba.ghtml',
    'lastmod': '2026-04-13T23:09:17.077000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/s7m8CCg1NnIj1YvwT-P1k69I-QU=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2023/X/T/cJnhLOTYW3kv1L7rc9Aw/forum.jpg'}},
   {'loc': 'https://g1.globo.com/mg/minas-gerais/noticia/2026/04/13/cristiano-machado-e-a-via-com-mais-acidentes-em-bh-veja-ranking.ghtml',
    'lastmod': '2026-04-13T23:07:00.225000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/Lx4AfYYI50PMpLdOIyT1d0rOilQ=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2025/0/C/EcN6W6Tiyo4ve2s2wVHA/globocop-bdmg-18-jun-2025-248-frame-44880.jpeg'}},
   {'loc': 'https://g1.globo.com/pa/para/noticia/2026/04/13/video-flagra-policial-civil-atirando-em-frente-a-clube-em-jacareacanga-no-pa.ghtml',
    'lastmod': '2026-04-14T12:51:02.247000+00:00'},
   {'loc': 'https://g1.globo.com/pa/para/noticia/2026/04/13/alepa-realiza-nova-audiencia-com-comunidades-e-promete-mais-rigor-na-analise-de-aterros-em-acara-e-bujaru-no-pa.ghtml',
    'lastmod': '2026-04-14T00:55:17.989000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/VzZotNl_Nyn1DP3YeZYvswNpVZc=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/W/c/BXimHLQWAxdwAdHBb6Nw/whatsapp-image-2026-04-13-at-18.17.42.jpeg'}},
   {'loc': 'https://g1.globo.com/to/tocantins/noticia/2026/04/13/entenda-a-prisao-do-motorista-suspeito-de-transportar-467-kg-de-cocaina-em-caminhao-carregado-de-abacaxi.ghtml',
    'lastmod': '2026-04-14T01:03:34.157000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/EtK-q_Udmt3i2riakAUxHLnr6KE=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/d/X/gqVMUvSVqZTuaxwT3C9A/whatsapp-image-2026-04-13-at-07.07.28.jpeg'}},
   {'loc': 'https://g1.globo.com/mg/sul-de-minas/edicao/2026/04/13/videos-eptv-2-sul-de-minas-de-segunda-feira-13-de-abril-de-2026.ghtml',
    'lastmod': '2026-04-13T23:02:30.201000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/4DkgQaXWx4TgaPNcg0IE7nwGlLk=/s01.video.glbimg.com/deo/vi/49/20/14522049'}},
   {'loc': 'https://g1.globo.com/go/goias/noticia/2026/04/13/maior-peixe-de-agua-doce-de-couro-do-brasil-e-que-pode-pesar-mais-de-200-kg-conheca-especie-que-nao-pode-ser-consumida-em-goias.ghtml',
    'lastmod': '2026-04-13T22:58:41.300000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/8bzO4ivs5zCGNYNzKgKkgGaGj_c=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/T/2/zkA4LwSfuRAw2igbRA3A/copia-de-copia-de-copia-de-padrao-foto-g1-goias.jpg'}},
   {'loc': 'https://g1.globo.com/pop-arte/noticia/2026/04/13/com-12-anos-north-west-filha-de-kanye-west-e-kim-kardashian-e-anunciada-em-festival-nos-eua.ghtml',
    'lastmod': '2026-04-13T22:58:13.850000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/oina-7Ge4W2VgM4cUqXHjBxiqp8=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/q/f/m9AWs6SWGGENJFP7dZzg/fotos-g1-26-.png'}},
   {'loc': 'https://g1.globo.com/pb/paraiba/noticia/2026/04/13/joao-pessoa-registra-volume-de-chuva-19percent-acima-da-media-historica-de-abril-em-menos-de-duas-semanas.ghtml',
    'lastmod': '2026-04-13T22:56:48.695000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/ujhQLzvqx3wYKWvSn0WNpQKlYH8=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2025/O/x/OHw5F7RBOpdmpMQ7ZVww/rain-in-john-person.jpeg'}},
   {'loc': 'https://g1.globo.com/sp/sao-paulo/noticia/2026/04/13/nao-me-deixaram-socorrer-minha-esposa-afirma-companheiro-de-mulher-morta-por-pm-na-zona-leste-de-sp.ghtml',
    'lastmod': '2026-04-13T22:57:46.984000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/keltJr-POhHt4VSLYnxS_ydi4p0=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/q/h/FY7ZvYQ8i0kx8i1QBEEw/fotojet-61-.jpg'}},
   {'loc': 'https://g1.globo.com/pr/parana/eleicoes/2026/noticia/2026/04/13/ratinho-junior-sandro-alex.ghtml',
    'lastmod': '2026-04-14T14:55:48.671000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/a0Kl6QEELC8Awn5EroEZY6gg7u4=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/i/W/UMidY2Svy9hhvvKB4YXg/httpsportalnorte.com.brwp-adminpost.phppost-292629-action-edit-16-.png'}},
   {'loc': 'https://g1.globo.com/sp/itapetininga-regiao/noticia/2026/04/13/suspeito-de-matar-jovem-de-25-anos-a-facadas-em-avare-e-preso-em-goias.ghtml',
    'lastmod': '2026-04-13T22:52:17.099000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/5HS73-f7ziI6-dOcLI29nS7ChNI=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/t/m/CgFjsARyiKNtNWXUDmkg/whatsapp-image-2026-04-13-at-16.14.40.jpeg'}},
   {'loc': 'https://g1.globo.com/rj/rio-de-janeiro/videos-rj2/playlist/videos-rj2-de-segunda-13-de-abril-de-2026.ghtml',
    'lastmod': '2026-04-13T22:50:26.558000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/2_UdmPv8Do82wBz2a_mByPznnPM=/s01.video.glbimg.com/deo/vi/47/19/14521947'}},
   {'loc': 'https://g1.globo.com/pr/norte-noroeste/noticia/2026/04/13/guarda-resgate-gato-tutora-presa-maus-tratos-pr.ghtml',
    'lastmod': '2026-04-13T22:49:36.813000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/kXi1MMyshht2ZFSfI8j7x8NDsZY=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/1/Y/DDDsPeQDqPQzbGBtNnvw/httpsportalnorte.com.brwp-adminpost.phppost-292629-action-edit-2026-04-13t193908.294.jpg'}},
   {'loc': 'https://g1.globo.com/ro/rondonia/noticia/2026/04/13/presidente-do-tj-ro-assume-interinamente-governo-de-rondonia-durante-viagem-de-marcos-rocha.ghtml',
    'lastmod': '2026-04-13T22:48:42.731000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/hLJYBlzbbb0_638ulxdEQSM1sHU=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/g/s/BspAnLTqCIEaD7vRC7xw/img-6818simone-edit.jpg'}},
   {'loc': 'https://g1.globo.com/pr/parana/noticia/2026/04/13/medico-adolescente-parana.ghtml',
    'lastmod': '2026-04-13T22:48:21.145000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/b37rO5b1wOfcwkBJ4G1ZpRuprAY=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/s/O/PPf3mLQTOhafF4fkHogQ/snapshot-1153.png'}},
   {'loc': 'https://g1.globo.com/sp/presidente-prudente-e-regiao/noticia/2026/04/13/trabalhador-de-48-anos-morre-apos-cair-em-tanque-de-peixe-no-interior-de-sp.ghtml',
    'lastmod': '2026-04-14T20:06:41.058000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/oPRIrqqITnG1UZb08YboKPAWwRU=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/n/L/48P8AwSeST4LPtEyIwwQ/1200-x-800-px-2-2026-04-13t184528.207.png'}},
   {'loc': 'https://g1.globo.com/rj/regiao-dos-lagos/noticia/2026/04/13/menino-de-7-anos-morre-com-hemorragia-e-traumatismo-craniano-apos-cair-de-arvore-fizeram-raio-x-do-braco-e-mandaram-para-casa.ghtml',
    'lastmod': '2026-04-14T00:00:05.181000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/MeDlA-9L_dgT7aq2dbROE2-Wx40=/i.s3.glbimg.com/v1/AUTH_59edd422c0c84a879bd37670ae4f538a/internal_photos/bs/2026/x/u/ggqa9MQ9yxRXfft1A57Q/upa.jpg'}},
   {'loc': 'https://g1.globo.com/pa/para/edicao/2026/04/13/videos-jl2-de-segunda-feira-13-de-abril-de-2026.ghtml',
    'lastmod': '2026-04-13T22:46:44.698000+00:00',
    'image:image': {'image:loc': 'https://s2-g1.glbimg.com/0bcFKYX2srdBQ1VX85DSUGP1Gbk=/s01.video.glbimg.com/deo/vi/06/19/14521906'}},
   {'loc': 'https://g1.globo.com/pi/piaui/noticia/2026/04/13/video-aves-silvestres-devolvidas-a-natureza.ghtml',
    'lastmod': '2026-04-13T22:44:18.006000+00:00',

In [6]:
locs = map(lambda x: x["loc"], data["urlset"]["url"])
locs

In [7]:
titles = list(map(lambda x: " ".join(x.split("/")[-1].split("-")[:-1]), locs))

In [8]:
print(len(titles))
for title in titles:
    print(title)

752
adolescente morre por h1n1 em
exportacoes recuam 2percent no primeiro trimestre de 2026 no vale do paraiba e regiao
trump chama leao xiv de fraco e pessimo papa reage e diz que vai seguir firme contra a
marilia sanciona lei que permite enterro de caes e gatos em jazigos de tutores projeto e aprovado na camara em
video onibus e destruido por incendio na br 364 em
medico e detido acusado de agredir companheira no interior de
apos pressao do governo projeto que regulamenta atividade de entregadores e motoristas sai de pauta na
zoologico de fortaleza vai fechar durante dois dias apos lotacoes registradas desde a
medico moto atingida
moradores reclamam de vizinho que acumula lixo e entulho em casa no acre extremamente
corregedoria do tribunal de justica do amazonas analisa omissao de juiz do careiro apos demora em decisao diz
pm da reserva tentar matar esposa a tiros e vitima escapa ao pular muro de casa e pedir socorro em bar de
apos dois anos policia federal ainda tenta identificar corpos encontrados em barco a deriva no
camara de bh aprova em 1o turno ampliacao de isencao de taxa para habitacoes
familia de empresario morto baleado em bar no rio de janeiro repudia versao de que vitima se envolveu em
videos ab2 de segunda feira 13 de abril de
videos do g1 e tv subae segunda feira 13 de abril de
mulher morta facadas briga vizinhos
videos ne2 de segunda feira 13 de abril de
uniao brasil em sp critica articulacao para ciro nogueira liderar federacao com pp e fala em risco de
ministerio publico ajuiza acao para preservar atividades da unincor em tres coracoes
acidente entre motos deixa dois feridos na br 393 em tres
buscas por homem que desapareceu em acude no agreste da pb sao suspensas e devem ser retomadas nesta terca
video assaltantes armados com um revolver roubam mercado e deixam prejuizo de r 1 mil no interior de
maior chacina do df primeiro dia de julgamento ultrapassa 10 horas juri sera retomado nesta
lacres de latinhas viram cadeiras de rodas para doacao em
acidentes em rodovias deixam feridos em lencois paulista e iacri motoristas sao
preso morre com meningite bacteriana e visitas sao suspensas no cdp de sao vicente diz
justica mantem condenacao reus tribunal crime
cristiano machado e a via com mais acidentes em bh veja
video flagra policial civil atirando em frente a clube em jacareacanga no
alepa realiza nova audiencia com comunidades e promete mais rigor na analise de aterros em acara e bujaru no
entenda a prisao do motorista suspeito de transportar 467 kg de cocaina em caminhao carregado de
videos eptv 2 sul de minas de segunda feira 13 de abril de
maior peixe de agua doce de couro do brasil e que pode pesar mais de 200 kg conheca especie que nao pode ser consumida em
com 12 anos north west filha de kanye west e kim kardashian e anunciada em festival nos
joao pessoa registra volume de chuva 19percent acima da media historica de abril em menos de duas
nao me deixaram socorrer minha esposa afirma companheiro de mulher morta por pm na zona leste de
ratinho junior sandro
suspeito de matar jovem de 25 anos a facadas em avare e preso em
videos rj2 de segunda 13 de abril de
guarda resgate gato tutora presa maus tratos
presidente do tj ro assume interinamente governo de rondonia durante viagem de marcos
medico adolescente
trabalhador de 48 anos morre apos cair em tanque de peixe no interior de
menino de 7 anos morre com hemorragia e traumatismo craniano apos cair de arvore fizeram raio x do braco e mandaram para
videos jl2 de segunda feira 13 de abril de
video aves silvestres devolvidas a
o globo entra para o guinness com edicao dos 100
empresario de 62 anos e morto a tiros perto de aterro sanitario em embu das
guia michelin novas estrelas
multidao saqueia carga apos carreta tombar em vitoria da
atendimentos especializados da policlinica do tucuma sao transferidos para nova maternidade em rio
jovem e preso apos denuncia de maus tratos e 15 animais sao resgatados em barra
prefeitura anuncia audiencia publica para concessao da rodoviaria de porto
casal encontrado morto em apartamento alugado em
carga milionaria de cigarros contrabandeados e apreendida na raposo tavares tres sao presos com medicamentos
motoristas param em local proibido e atrapalham passagem de ambulancias em
jovem morre e irmao fica ferido apos colisao frontal enquanto davam grau com motos no
chuva forte causa alagamentos em varias ruas de belem e derruba muro de supermercado
videos mg2 de segunda feira 13 de abril de
escala 6x1 lula vai almocar com motta nesta terca antes de enviar projeto do governo a
videos gr2 de segunda feira 13 de abril de
preso segundo envolvido no assassinato de jovens na
homem e preso em manaus por agredir ex namorada enquanto ela segurava filho no
video festa em casa de apoio a pessoas com cancer em jaiba causa demissao de
homem que levou choque apos queda de poste e teve 50percent do corpo atingido aguarda transferencia para hospital de
rondoniense morre apos acidente de moto em
apos casa onde houve acidente com cesio 137 virar estacionamento vasos de plantas sao instalados para evitar entrada de carros
patrao e indiciado pelos crimes de importunacao e assedio sexual contra
governador em exercicio exonera presidente interino do rioprevidencia apos recomendacao do
dois dos quatro atendimentos hospital jovem gravida morreu falhas
barragem do cipo em caruaru sera demolida apos estudos apontarem alto risco
servidor atropela e mata cachorro com trator
homem morre atacado por
juiz rejeita acao de trump contra jornal por reportagem sobre sua ligacao com
barragem oiticica metade
museu sacaca celebra 24 anos com programacao especial em
maes de alunos fazem manifestacao apos bebe de 1 ano voltar da creche com hematomas e fratura no
pesquisa e momento diz alckmin apos datafolha mostrar empate entre lula e flavio
baixada santista restaurant week tem pratos inspirados na copa do mundo a precos fixos confira os
preso anderson torres deve depor por video em acao sobre criacao ilegal de aves silvestres no
sindromes respiratorias agudas graves causam 28 mortes no norte de
homem e preso apos mostrar o penis para mulher em rua ele ja tinha passagem por importunacao
coletivo de mulheres negras do interior da bahia lanca livro na
filho diz que matou padrasto para vingar mae atropelada mas familia contesta e relata
ocorrencias
claudio castro diz que faltara a cpi do crime organizado por lombalgia
jovens ficam presos em caverna por mais de 8h durante trilha
policia prende suspeito de matar homem a facadas dentro de mercado no agreste da
supermercado oferece 200 vagas de emprego em campinas veja como se
esposa de ramagem segue em ferias da pge rr apos viagem aos eua mas ainda precisa explicar ausencia sem afastamento
mulher internada em estado grave por suspeita de envenenamento e transferida filha de 6 anos
domo de calor e pouca chuva marcam o tempo no triangulo e alto
quem era a servidora publica que foi morta e teve dedo decepado em sp filho foi
suspeito de matar homem esfaqueado no quintal de casa e preso apos policia seguir pegadas no interior de
familia morreu acidente br 116 pr morava sc veja quem eram pai mae
homem e preso com carro roubado e adulterado na castello branco em
adolescente desaparece apos cair em rio ao atravessar passarela no acre
motorista e condenado a 22 anos por matar homem a tiros em dom
homem e morto com mais de 15 tiros em pedras de fogo pb mulher fica ferida durante
parque nacional da tijuca bate recorde de visitantes em
edital para eleicao de governador e vice no amazonas e divulgado pela assembleia entenda como vai
morre jovem atropelada em avenida de
assista a missa de encerramento da festa da penha
homem morre queda concreto construcao predio pre moldado
onibus e invadido por agua durante chuva forte em campo grande veja
menopausa serie do sp1 explica impactos a saude da
motorista morre tentar soltar caminhao preso fios
video acidente entre moto e bicicleta deixa dois feridos em
suspeito de arrancar parte da lingua de ex companheira em aracaju e
eduardo leite entrevista
porsche bate em duas motos e deixa tres feridos
carmen lucia afirma que stf enfrenta momento de tensao e precisa ampliar
delegado aposentado e investigado por violencia domestica contra esposa e policial militar no interior de
hospitais municipais na barra e iraja promovem doacao de
vitoria cria regras para bicicletas eletricas patinetes e ciclomotores veja o que
arthur do val pede desculpas ao povo sergipano apos falas ofensivas ao reagir a anuncio de show com uso de verba parlamentar em
nasa fotos lua artemis
apos acidente com caminhao que interrompeu viagens operacao dos trens so deve ser normalizada na terca feira no
lider religioso e condenado a 8 anos de prisao por abusar sexualmente de fieis em
justica decreta prisao preventiva de mulher acusada de tentar matar namorado com acai envenenado em ribeirao preto
homem e encontrado morto apos tentar atravessar acude no sertao da
obra previsivel como padronizacao reduz retrabalho em
contribuintes de araraquara podem destinar parte do imposto de renda para
prefeitura de brumado assume administracao de clinica de hemodialise apos
telefonia fixa empresarial volta ao centro das operacoes
editais de intimacao de limpeza em terrenos e calcadas sao
chuva forte causa alagamentos em varias ruas de belem e derruba muro de
video idosa e agredida e derrubada por ladrao em calcada de
sesi ma abre seletivos com 10 vagas para niveis medio e superior salarios podem chegar a r 52
animador de festas para criancas e preso por exploracao sexual infantil em
catarinense parto ponte hercilio luz
instabilidade acelera revisao da telefonia empresarial nas
idosa amarrada
corpo de turista mineiro e encontrado apos ser arrastado pelo mar em arraial do cabo no dia do
em protesto contra mineradora por falta de indenizacao comunidade interdita rodovia em
sao jose dos pinhais inova com educacao digital no curriculo
paula fernandes anuncia show com participacoes de ana castela simone mendes e padre fabio de melo em
telefonia como servico cresce e reduz custos nas
onca parda retorna ao zoologico de volta redonda apos
quem kauan santos turista morreu apos se afogar em
dolar abaixo de r 5 o que explica a queda da moda
rodovia tem desvio para pista nova nesta terca no interior de sp veja o que
governo anuncia reabertura da sala principal do tca apos
senacon investiga recusa do brb em cancelar debitos automaticos salarios foram
carlinhos maia e multado em r 1 milhao por infracao ambiental em noronha em fernando de
moradores denunciam que pulverizacao de agrotoxicos destruiu plantacoes e contaminou agua em duque
que ele venha ter paz diz esposa de motorista morto em briga de transito em
como a experiencia internacional pode capacitar os futuros
com participacao de alckmin governo de sp formaliza emprestimo de r 26 bilhoes para obras do tunel santos
vai vender seu imovel veja por que escolher a imobiliaria
advogado perde r 12 mil ao cair em golpe da maquininha durante show do guns n roses em rio
embriaguez alta velocidade e direcao perigosa motorista e indiciado por homicidio doloso apos morte na avenida rondon
tres casos de esfaqueamento deixam um morto e dois feridos no mesmo fim de semana no norte
cubatao inaugura espaco que troca reciclaveis por produtos e servicos
adolescente de 16 anos e encontrado morto em lago na zona rural de pilar do
obra parintins a cor da minha raca e escolhida como tela oficial do festival folclorico de
caso nicolly policia investiga se assassinato foi incitado ou transmitido na internet diz
motociclista morre e homem fica em estado grave apos acidente com caminhao na br 494 em
homem e morto a tiros na regiao sul de
caminhoneiro e feito refem e trancado em bau apos roubo de carga de r 157 mil em
ambulancia pega
policia investiga relacao entre idoso e jovem morta a facadas em
justica condena estado de pe a pagar r 300 mil a filhos de vitima de feminicidio apos fuga de
videos bom dia acre desta segunda feira 13 de abril de
cesio 137 projeto pretende criar feriado para homenagear vitimas do acidente em
justica aceita denuncia de crime ambiental contra bar na orla de joao
criminosos envolvidos no ataque a cidade de mt tem historico em grandes crimes no brasil e no
mec livros a cabeca do santo lidera procura em biblioteca digital e ceara e o 4o estado com mais
festival de curitiba movimenta r 50 milhoes e atrai 200 mil
sao joao no distrito de sao jose em feira de santana tera um dia a mais de programacao confira as
centenas de cafes gratis marcam o dia mundial do cafe no jockey plaza
bombeiros buscam jovem de 28 anos que desapareceu no mar na praia campista em
mulher cai de passarela na br 101 na grande
de olho no show no rio shakira prova comidas
juiz de fora tera semana sem chuva e com friozinho pelas manhas veja
mais de 60 galos sao resgatados e homem e preso durante operacao contra rinha no sertao da
decisoes judiciais sul de
delegado brasileiro que atua no ice contribuiu para prisao de ramagem nos eua diz
antes de matar um e ferir tres suspeito foi diagnosticado com esquizofrenia e fugiu de
quem era renato salles jornalista que morreu aos 47 anos em juiz de
perito aponta que cachorro pode ter dilacerado corpo de mulher achada morta em mogi das
arvores centenarias pr argentina
por que gigantes de tecnologia estao investindo em energia
operacao descobriu endereco de ramagem nos eua depois de localizar carro usado para buscar esposa no
embraer abre 160 vagas para curso gratuito de auxiliar de producao aeronautica veja como
caminhao tomba e policia encontra mais de 470 kg de drogas em carga de fertilizante na ms
alexandre fraga escritor e criador da seria
homem e preso apos perseguicao da gcm em mogi das
estudantes de universidade particular atacam homem em situacao de rua com arma de choque em
certidoes de nascimento sao emitidas para indigenas de
carro capota apos bater em ciclovia na avenida 28 de marco em
homem arremessa companheira de carro em movimento deixa mulher ferida e e preso em
estudante de direito e preso suspeito de dar socos e espancar namorada dentro de carro em predio em goiania
deputado ismael crispin sofre acidente apos veiculo aquaplanar na br 429 em
festival de curitiba publico aponta favoritos da
video flagra abordagem de pm a entregador durante blitz no ac fiquei com
aposentadoria nao e sorte saiba por que planejamento faz diferenca no
homem agride companheira enteado e filha de 2 anos em
suspeita e presa por esfaquear e atear fogo em companheiro em
semana dos povos indigenas tem trilhas na floresta oficinas filmes e debates gratuitos no museu
rdd produtor musical que deu forma eletronica ao pagodao baiano vai alem do genero no album solo hot
homem preso
lula anuncia paulo pimenta novo lider do governo na
objetos furtados em loja de santarem sao recuperados em belterra suspeita responde em
estrelas de hollywood assinam carta aberta contra acordo entre paramount e warner
vereador e feito refem por tres suspeitos durante roubo em casa no interior de
apos repercussao justica federal diz que nao determinou destruicao de igreja de mais de 400 anos em
mais de 700 caes e gatos sao vacinados contra raiva durante mutirao em rio
em 6 dias 200 toneladas de maconha sao apreendidas em operacao na fronteira entre paraguai e
rede amazonica anuncia data para o saude de rua 2026 em boa
quadrilha morte pm sorocaba origem
videos jornal do acre 1 edicao desta segunda feira 13 de abril de
videos jornal anhanguera 1 edicao to de segunda feira 13 de abril de
dividindo racao com
com estoque em alerta hemonucleo de barra mansa pede doacoes veja como e onde
empresaria servicos de home care e
em mojui dos campos emater auxilia agricultores para acesso a credito e minha casa
saiba quem e o americano pai de agente do fbi preso suspeito de comandar laboratorio de drogas no
moroni nascimento e destaque da cbksi e eleva o nome do brasil no karate
mulher morre atropelada em rodovia de bauru motorista recusa
corpo de bombeiros localiza corpo de jovem que se afogou ao tentar buscar jet ski em represa no interior de
policia prende homem suspeito de dever mais de r 34 mil em pensao alimenticia em
buday santos e campeao do circuito de surfe de fernando de
incendio atinge panificadora de supermercado em
video carro pega fogo perto de escola no bairro maravilha em
crianca de 1 ano morre apos ser encontrada em piscina em marilia suspeita e de
acidente com tres carros deixa um morto e dois feridos na rj 216 em
mergulhador morre alto mar
foz do iguacu no outono clima ideal e experiencias para aproveitar a
professor da rede municipal de triunfo e preso por suspeita de abusos sexuais contra
jovem de 19 anos e preso suspeito de envolvimento em estupro coletivo contra menina de 12 anos em sao jose dos
dois idosos e crianca de 7 anos morrem em acidente de transito em
eleicoes 2026 tre abre inscricoes para mesarios em mais de 8 mil secoes eleitorais de mt veja
suspeitos de homicidio e tentativa de homicidio contra irmaos em contagem sao presos em
editais para obras em trechos da br 319 sao publicados veja
justica decreta prisao preventiva de operador do minhocao e de dono do parque onde jovem morreu em
por que donald trump decidiu bloquear o estreito de ormuz apos tanto defender a abertura
governo do estado fortalece rede de cultura e amplia presenca em todo o
sesc vagas cursos
mega sena 2995 26 apostas de alagoas acertam a quadra veja
capela de sao pedro e invadida por criminosos pela quarta vez nos ultimos tres anos em sao
balneario buraco
lagoa do taquaral em campinas tem 22 lixeiras danificadas apos
pm e morto a tiros em duque de caxias na baixada
casamento coletivo tem 100 vagas abertas em assis brasil veja
bebe de 1 ano volta da creche com hematomas e fratura no
homem que matou vizinha com marteladas na cabeca no litoral de sp se entrega a policia em
deputado lucas bove vira reu em 2o processo envolvendo influencer cintia chagas agora por descumprir 10 medidas
videos jornal anhanguera 1 edicao regioes desta segunda feira
mutirao de emissao de
carreta da mulher faz mais de 670 exames e amplia diagnostico precoce do
homem e preso com armas e municoes apos tentativa de
carro capota durante perseguicao policial e deixa dois jovens feridos em coronel
amazonas registra mais de mil acidentes de transito atendidos pelos bombeiros em 2025 media e de 3 por
condenada por tentar matar vizinha com veneno e sequestrar bebe e presa escondida em cama box em
dia d da campanha declare certo 2026 leva orientacoes fiscais a populacao de
idoso encontrado com larvas no corpo e em situacao grave segue internado em hospital de
cadela que precisou passar por cirurgia apos ser abusada recebe alta e volta para casa em boa
mineiro que desapareceu em praia do rj foi puxado por onda e nao sabia nadar diz
e fake que astronauta da artemis ii seja atriz contratada pela nasa e tenha esquecido falas em entrevista apos retorno a
imagens mostram casa onde ramagem estaria morando na florida
interior do norte de sc se consolida como polo de atracao para investimentos
estudantes de santarem representam o municipio em congresso nacional da ubes em sao
quem era o professor morto em acidente de transito no sul de
jovem morre e causa comocao em anapolis pessoa incrivel e de otimo
justica converte prisao em flagrante em preventiva de soldado que matou colega em condominio militar na zona sul de
videos jl1 de segunda feira 13 de abril de
unidade popular lanca juliete pantoja como pre candidata ao governo do
videos bdp de segunda feira 13 de abril de
equipe de katy perry nega acusacoes de assedio feitas por ruby rose mentiras
cemig inaugura nova agencia de atendimento em juiz de fora veja servicos
empresa de producao de celulose abre inscricoes para programa de estagio de nivel superior na
lindbergh farias entrevista
evento geek gratuito em feira de
operacao contra poluicao sonora apreende carros com paredoes em sao
video assalto a padaria no interior do
artefato explosivo e encontrado em
jacare aparece nadando em piscina de condominio em aldeia

In [9]:
import spacy

/home/rafael-albuquerque/repos/tcc/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [10]:
nlp = spacy.load("pt_core_news_sm")

In [11]:
import pandas as pd

In [12]:
x = nlp(titles[0])

print(x.ents)
for token in x:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
          token.shape_, token.is_alpha, token.is_stop)

(h1n1,)
adolescente adolescente ADV ADV advmod xxxx True False
morre morrer VERB VERB ROOT xxxx True False
por por ADP ADP case xxx True True
h1n1 h1n1 NOUN NOUN obl xdxd False False
em em ADP ADP dep xx True True

In [13]:
subset = titles[:20]

In [14]:
df = pd.DataFrame(subset, columns=["title"])
df["entities"] = df["title"].apply(lambda x: nlp(x).ents)
df

,title,entities
0,adolescente morre por h1n1 em,"((h1n1),)"
1,exportacoes recuam 2percent no primeiro trimes...,"((exportacoes),)"
2,trump chama leao xiv de fraco e pessimo papa r...,"((trump, chama, leao, xiv, de, fraco),)"
3,marilia sanciona lei que permite enterro de ca...,"((marilia), (camara))"
4,video onibus e destruido por incendio na br 36...,"((br, 364),)"
5,medico e detido acusado de agredir companheira...,()
6,apos pressao do governo projeto que regulament...,()
7,zoologico de fortaleza vai fechar durante dois...,()
8,medico moto atingida,()
9,moradores reclamam de vizinho que acumula lixo...,"((acre),)"
10,corregedoria do tribunal de justica do amazona...,"((amazonas),)"
11,pm da reserva tentar matar esposa a tiros e vi...,()
12,apos dois anos policia federal ainda tenta ide...,()
13,camara de bh aprova em 1o turno ampliacao de i...,()
14,familia de empresario morto baleado em bar no ...,"((familia), (rio, de, janeiro))"
15,videos ab2 de segunda feira 13 de abril de,"((ab2),)"
16,videos do g1 e tv subae segunda feira 13 de ab...,"((g1),)"
17,mulher morta facadas briga vizinhos,()
18,videos ne2 de segunda feira 13 de abril de,()
19,uniao brasil em sp critica articulacao para ci...,"((brasil), (sp), (ciro, nogueira))"

In [15]:
import ollama

In [16]:
def rewrite_title(title):
    client = ollama.Client("http://192.168.0.12:11434")
    prompt = "Reescreva o título da notícia com base nessa versão extraída de uma URL. Esse texto não tem capitalização e nem pontuação, e é sua responsabilidade adicionar capitalização e pontuação onde for adequado.\nTexto original: {}\nTexto reescrito: ".format(title)
    response = client.generate("llama3.2:3b", prompt).response
    return response

In [21]:
df["rewritten_title"] = df["title"].apply(rewrite_title)
df

,title,entities,rewritten_title
0,adolescente morre por h1n1 em,"((h1n1),)",Adolescente Morre Por H1N1 Em
1,exportacoes recuam 2percent no primeiro trimes...,"((exportacoes),)","""Exportações Recuam 2% no Primeiro Trimestre d..."
2,trump chama leao xiv de fraco e pessimo papa r...,"((trump, chama, leao, xiv, de, fraco),)","Trump chama Léonidas XIV de fraco e péssimo, P..."
3,marilia sanciona lei que permite enterro de ca...,"((marilia), (camara))","""Marília Sanciona Lei que Permite Enterro de C..."
4,video onibus e destruido por incendio na br 36...,"((br, 364),)","""VIDEO: ONIBUS DESTRUIDO POR INCÊNDIO NA BR 364"""
5,medico e detido acusado de agredir companheira...,(),"""Ação contra médico que detido por acusado de ..."
6,apos pressao do governo projeto que regulament...,(),"""A Pauta do Governo: Projeto que Regula Ativid..."
7,zoologico de fortaleza vai fechar durante dois...,(),"""Zoológico de Fortaleza Fecha por Dois Dias Ap..."
8,medico moto atingida,(),Claro! Aqui está a versão reescrita do título ...
9,moradores reclamam de vizinho que acumula lixo...,"((acre),)","""Moradores Reclamam de Vizinho com Lixo e Entu..."
10,corregedoria do tribunal de justica do amazona...,"((amazonas),)","""Corregedoria do Tribunal de Justiça do Amazon..."
11,pm da reserva tentar matar esposa a tiros e vi...,(),"""PM da Reserva Tenta Matar Esposa a Tiros, Vít..."
12,apos dois anos policia federal ainda tenta ide...,(),"""APOS DOIS ANOS, POLICIA FEDERAL COMEÇA A TENT..."
13,camara de bh aprova em 1o turno ampliacao de i...,(),"""Câmara de BH Aprova Em 1º Turno Ampliação de ..."
14,familia de empresario morto baleado em bar no ...,"((familia), (rio, de, janeiro))","Aqui está a versão final do título:\n\n""Family..."
15,videos ab2 de segunda feira 13 de abril de,"((ab2),)","""Vídeos do dia de semana 2 de abril de 2023"""
16,videos do g1 e tv subae segunda feira 13 de ab...,"((g1),)","""Vídeos do G1 e TV Subª: Segunda-feira, 13 de ..."
17,mulher morta facadas briga vizinhos,(),"""Mulher Morta com Facadas em Briga com Vizinho..."
18,videos ne2 de segunda feira 13 de abril de,(),"""Vídeos novos na Segunda-feira, 13 de Abril de..."
19,uniao brasil em sp critica articulacao para ci...,"((brasil), (sp), (ciro, nogueira))","""União do Brasil em SP Critica Articulação par..."

In [20]:
for i, title, rt in df[["title", "rewritten_title"]].itertuples():
    print(f"{i} | {title} | {rt}")

0 | adolescente morre por h1n1 em | "Adolescente morre por h1n1."
1 | exportacoes recuam 2percent no primeiro trimestre de 2026 no vale do paraiba e regiao | "Exportações Recuam 2% no Primeiro Trimestre de 2026, diz Estudo do Vale do Paraíba e Região."
2 | trump chama leao xiv de fraco e pessimo papa reage e diz que vai seguir firme contra a | "Trump chama Leão XIV de fraco e pobre, Papa - Reação do Papa Pio XI."
3 | marilia sanciona lei que permite enterro de caes e gatos em jazigos de tutores projeto e aprovado na camara em | Marilia Sanciona Lei que Permite Enterro de Cães e Gatos em Jazigos de Tutores, Projeto e Aprovado na Câmara.
4 | video onibus e destruido por incendio na br 364 em | "Vídeo: Ônibus destruído por incêndio na BR-364".
5 | medico e detido acusado de agredir companheira no interior de | "Medico Detido Acusado de Agredir Companheira no Interior"

Essa é uma versão reescrita do título com base na versão extraída da URL, adicionando capitalização e pontuação para torná-la mais legível.
6 | apos pressao do governo projeto que regulamenta atividade de entregadores e motoristas sai de pauta na | "Apos Pressão do Governo, Projeto que Regulamenta Atividade de Entregadores e Motoristas Sai de Pauta"
7 | zoologico de fortaleza vai fechar durante dois dias apos lotacoes registradas desde a | Aqui está a versão revisada do título:

"Zoológico de Fortaleza Vai Fechar por Dois Dias Após Lotações Registradas desde Amanhã"
8 | medico moto atingida | "Médico Moto Atingida"
9 | moradores reclamam de vizinho que acumula lixo e entulho em casa no acre extremamente | "Moradores reclamam do vizinho que acumula lixo e entulho em sua casa no Acre Extremamente Desorganizado"
10 | corregedoria do tribunal de justica do amazonas analisa omissao de juiz do careiro apos demora em decisao diz | A Corregedoria do Tribunal de Justiça do Amazonas Analisa Omissão de Juiz no Careiro Após Demora em Decisão, diz.
11 | pm da reserva tentar matar esposa a tiros e vitima escapa ao pular muro de casa e pedir socorro em bar de | "PM da Reserva Tenta Matar Esposa a Tiros, Vítima Escapa Pular Muro e Pedir Socorro em Bar de"
12 | apos dois anos policia federal ainda tenta identificar corpos encontrados em barco a deriva no | "Apos dois anos, a polícia federal ainda tenta identificar os corpos encontrados em um barco a deriva."
13 | camara de bh aprova em 1o turno ampliacao de isencao de taxa para habitacoes | "Camara de BH aprovaa em 1º turno ampliação da isenção de taxa para habitações."
14 | familia de empresario morto baleado em bar no rio de janeiro repudia versao de que vitima se envolveu em | "Rio de Janeiro: Família do Empresário Morto Baleado em Bar Repudia Versão Sobre Vítima"

ou, alternativamente:

"Família do Empresário Morto por Bala no Rio de Janeiro Repudia a Teoria da Vítima"
15 | videos ab2 de segunda feira 13 de abril de | "Vídeos Ab2 de Segunda-feira, 13 de Abril de 2023"
16 | videos do g1 e tv subae segunda feira 13 de abril de | "Vídeos do G1 e TV Subaé na segunda-feira, 13 de abril."
17 | mulher morta facadas briga vizinhos | Aqui está o título reescrito com base na versão extraída da URL:

"Mulher Morta por Facadas em Briga com Vizinhos"

Espero que isso seja útil! Se precisar de mais ajuda, basta perguntar.
18 | videos ne2 de segunda feira 13 de abril de | "Vídeos do dia 2 de segunda-feira, 13 de abril de"
19 | uniao brasil em sp critica articulacao para ciro nogueira liderar federacao com pp e fala em risco de | "União Brasil em SP Critica Articulação para Ciro Nogueira Liderar Federação com PP; Fala no Risco do Movimento."